#!/bin/sh

# neko sources files depending on arguments
# shellcheck source=/dev/null
# some variables are sourced from the specified template
# shellcheck disable=SC2154
# Unused variables left for readability
# shellcheck disable=SC2034

root_base_dir="${DESTDIR}"/usr/local/share/neko
root_pkgs_dir="${root_base_dir}"/srcpkgs
root_src_dir="${root_base_dir}"/src
root_master_dir="${root_master_dir}"/master
root_license_dir="${root_base_dir}"/licenses
root_db_dir="${root_base_dir}"/db

base_dir="${XDG_DATA_HOME:-$HOME/.local/share}"/neko
pkgs_dir="${base_dir}"/srcpkgs
src_dir="${base_dir}"/src
master_dir="${base_dir}"/master
licenses_dir="${base_dir}"/licenses
db_dir="${base_dir}"/db

trap interrupt 2

neko_msg()
{
	case "${1}" in
		"normal") printf "%s\n" "[1m=> [36mneko:[0m ${2}" ;;
		"success") printf "%s\n" "[1m=> [32mneko:[0m ${2}" ;;
		"warning") printf "%s\n" "[1m=> [33mneko:[0m ${2}" ;;
		"error") printf "%s\n" "[1m=> [31mneko:[0m ${2}" ;;
	esac
}

usage()
{
	printf "%s\n%s\n" "Usage: ${0} command [target]" "See ${0} help"
	exit
}

help()
{
	cat << _EOF
[1musage[0m
${0} command [target]

[1mcommand[0m:
init
	Initializes the environment for use with the templates - must be run before
	packaging from templates.
pkg
	Checks to see if the <target> can be properly packaged from the template.
em | emerge
	Emerges the <target>. Will build and install it to the system.
uninstall
	Will uninstall <target> to the system.
find
	Will search for the <target>
clean
	Cleans up the master directory.
zap
	Will remove everything from the neko directory - you must run neko init
	after doing so.
help
	Displays this message

[1mstatus[0m:
Neko will have different colors depending on the status:
$(neko_msg normal "This is a normal message.")
$(neko_msg success "This is a successful message.")
$(neko_msg warning "This is a warning message.")
$(neko_msg error "This is an error message.")
_EOF
}

interrupt()
{
	# to start on a new line
	echo ""
	neko_msg error "Command interrupted"
	exit 2
}

# pkg_install are only used in templates
pkg_install()
{
	case "${1}" in
		"bin")
			echo "Installing $(basename "${2}")..."
			if
				mkdir -p "${DESTDIR}${PREFIX}"/bin
				cp -R "${2}" "${DESTDIR}${PREFIX}"/bin
				chmod 755 "${DESTDIR}${PREFIX}"/bin/"$(basename "${2}")"
			then
				echo "Successfully installed ${2}"
			else
				echo "Failed to install ${2}"
			fi
			;;
		"man")
			echo "Installing $(basename "${2}")..."
			if
				mkdir -p "${DESTDIR}${PREFIX}"/share/man/man"${3:-1}"
				cp -R "${2}" "${DESTDIR}${PREFIX}"/share/man/man"${3:-1}"
				chmod 644 "${DESTDIR}${PREFIX}"/share/man/man"${3:-1}"/"$(basename "${2}")"
			then
				echo "Successfully installed ${2}"
			else
				echo "Failed to install ${2}"
			fi
			;;
		"lib")
			[ "${2}" = "pkgconfig" ] &&
				{
					find . -name "*.pc" |
						while read -r line
						do
							printf "%s\n" "Installing $(basename "${line}")..."
							if
								mkdir -p "${DESTDIR}${PREFIX}"/lib/pkgconfig
								cp -r "${line}" "${DESTDIR}${PREFIX}"/lib/pkgconfig/"$(basename "${line}")"
								chmod 755 "${DESTDIR}${PREFIX}"/lib/pkgconfig/"$(basename "${line}")"
							then
								printf "%s\n" "Successfully installed ${line}"
							else
								printf "%s\n" "Failed to install ${line}"
							fi
						done
						return
				}
			find . -name "${2}" |
				while read -r line
				do
					printf "%s\n" "Installing $(basename "${line}")..."
					if
						mkdir -p "${DESTDIR}${PREFIX}"/lib
						cp -r "${line}" "${DESTDIR}${PREFIX}"/lib
						chmod 755 "${DESTDIR}${PREFIX}"/lib/"$(basename "${line}")"
					then
						printf "%s\n" "Successfully installed ${line}"
					else
						printf "%s\n" "Failed to install ${line}"
					fi
				done
			;;
		"inc")
			printf "%s\n" "Installing $(basename "${2}")..."
			if
				mkdir -p "${DESTDIR}${PREFIX}"/include
				cp -R "${2}" "${DESTDIR}${PREFIX}"/include
				# FIXME
				# If it runs on a folder, chaos happens with permissions
				# Fix will probably involve the find command
				#chmod 644 "${DESTDIR}${PREFIX}"/include/"$(basename "${2}")"
			then
				printf "%s\n" "Successfully installed ${2}"
			else
				printf "%s\n" "Failed to install ${2}"
			fi
			;;
		"conf")
			echo "Installing $(basename "${2}")..."
			if
				mkdir -p "${DESTDIR}${PREFIX}"/etc"${3}"
				cp -R "${2}" "${DESTDIR}${PREFIX}"/etc"${3}"
				chmod 644 "${DESTDIR}${PREFIX}"/etc"${3}"/"$(basename "${2}")"
			then
				echo "Successfully installed ${2}"
			else
				echo "Failed to install ${2}"
			fi
			;;
		"file")
			pkg_install file README 644 /usr/share/doc
			echo "Installing $(basename "${2}")..."
			if
				mkdir -p "${DESTDIR}${PREFIX}${4}"
				cp -R "${2}" "${DESTDIR}${PREFIX}${4}"
				chmod "${3}" "${DESTDIR}${PREFIX}${4}"/"${2}"
			then
				echo "Successfully installed $(basename "${2}")"
			else
				echo "Failed to install $(basename "${2}")"
			fi
			;;
	esac
}

neko_init()
{
	for dir in "${base_dir}" "${pkgs_dir}" "${src_dir}" "${master_dir}"\
		"${licenses_dir}" "${db_dir}"
	do
		[ ! -d "${dir}" ] && neko_msg normal "Making dir ${dir}..." &&
			if
				mkdir -p "${dir}"
			then
				neko_msg success "Successfully made dir ${dir}"
			else
				neko_msg error "Failed to make dir ${dir}"
				exit
			fi
	done
	neko_msg normal "Copying base srcpkgs to ${base_dir}..."
	if
		cp -R srcpkgs "${base_dir}"
	then
		neko_msg success "Successfully copied base srcpkgs to ${base_dir}"
	else
		neko_msg error "Failed to copy base srcpkgs to ${base_dir}"
		exit
	fi
	neko_msg normal "Copying licenses to ${base_dir}..."
	if
		cp -R licenses "${base_dir}"
	then
		neko_msg success "Successfully copied licenses to ${base_dir}"
	else
		neko_msg error "Failed to copy licenses to ${base_dir}..."
		exit
	fi
}

neko_zap()
{
	neko_msg normal "Zapping neko directory ${base_dir}..."
	if
		rm -rf "${base_dir:?}"/*
	then
		neko_msg success "Successfully zapped neko directory"
	else
		neko_msg error "Failed to zap neko directory"
		exit
	fi

}

neko_prepare()
{
	[ ! -d "${pkgs_dir}" ] && [ ! -d "${root_pkgs_dir}" ] &&
		{
			neko_msg error "No base srcpkgs found in ${base_dir}"
			neko_msg normal "Run neko init"
			exit
		}
	[ ! -d "${master_dir}" ] && [ ! -d "${root_master_dir}" ] &&
		{
			neko_msg error "No master dir found in ${base_dir}"
			neko_msg normal "Run neko init"
			exit
		}
	[ ! -d "${src_dir}" ] && [ ! -d "${root_src_dir}" ] &&
		{
			neko_msg error "No master dir found in ${base_dir}"
			neko_msg normal "Run neko init"
			exit
		}
	[ ! -d "${licenses_dir}" ] && [ ! -d "${root_license_dir}" ] &&
		{
			neko_msg error "No master dir found in ${base_dir}"
			neko_msg normal "Run neko init"
			exit
		}
	[ ! -d "${db_dir}" ] && [ ! -d "${root_db_dir}" ] &&
		{
			neko_msg error "No databse dir found in ${base_dir}"
			neko_msg normal "Run neko init"
			exit
		}
	if [ -f "${pkgs_dir}"/"${1}"/template ]
	then
		template_file="${pkgs_dir}"/"${1}"/template
		patches_dir="${pkgs_dir}"/"${1}"/patches
		files_dir="${pkgs_dir}"/"${1}"/files
		source_dir="${src_dir}"
		database="${base_dir}"/db
	elif [ -f "${root_pkgs_dir}"/"${1}"/template ]
	then
		template_file="${root_pkgs_dir}"/"${1}"/template
		patches_dir="${root_pkgs_dir}"/"${1}"/patches
		files_dir="${root_pkgs_dir}"/"${1}"/files
		source_dir="${root_src_dir}"
		database="${root_base_dir}"/db
	else
		neko_msg error "No template found for ${1}"
		exit
	fi
	. "${template_file}"
	if [ "${distfiles}" ]
	then
		wrksrc="${pkgname}"-"${version}"
	elif [ "${giturl}" ]
	then
		wrksrc="$(echo "${pkgname}" | sed 's/-git//')"
	fi
	archive="${distfiles##*/}"
	# Allow override of wrksrc and archive from the template
	. "${template_file}"
}

neko_fetch()
{
	# Remove duplicate wrksrc
	{
		[ -n "${distfiles}" ] || [ -n "${giturl}" ]
	} && [ -d "${source_dir}"/"${wrksrc}" ] && [ "${build_style}" != "meta" ] &&
		rm -rf "${source_dir:?}"/"${wrksrc:?}"
	# Remove duplicate archive
	[ "${distfiles}" ] && [ -f "${source_dir}"/"${archive}" ] &&
		[ "${build_style}" != "meta" ] && rm -rf "${source_dir:?}"/"${archive:?}"
	cd "${source_dir}" || exit
	[ "${build_style}" = "meta" ] && return
	neko_msg normal "Downloading source for ${1}..."
	if [ "${distfiles}" ]
	then
		if
			wget "${distfiles}"
		then
			neko_msg success "Successfully fetched distfiles for ${1}"
		else
			neko_msg error "Failed to fetch distfiles for ${1}"
			exit
		fi
	elif [ "${giturl}" ]
	then
		if
			git clone "${giturl}"
		then
			neko_msg success "Successfully cloned git repo for ${1}"
		else
			neko_msg error "Failed to clone git repo for ${1}"
			exit
		fi
	else
		[ "${build_style}" != "meta" ] &&
			{
				neko_msg warning "No distfiles or giturl specified"
				return
			}
	fi
}

neko_extract()
{
	[ "${build_style}" = "meta" ] && return
	[ "${distfiles}" ] && neko_msg normal "Extracting distfiles for ${1}..."
	[ "${distfiles}" ] &&
		if
			case "${archive##*.}" in
				"gz" | "tgz")
					tar -zxvf "${archive}"
					;;
				"bz2" | "xz")
					tar -xvf "${archive}"
					;; 
			esac
		then
			neko_msg success "Successfully extracted distfiles for ${pkgname}"
		else
			neko_msg error "Failed to extract distfiles for ${pkgname}"
			exit
		fi
	# Testing for replacing GNU tar with dd and od commands
	[ -n "${distfiles}" ] &&
		case "$(od -N 2 -t x2 "${archive}" | head -n 1 | sed 's/^.*\ //')" in
			"8b1f")
				neko_msg normal "${archive} is a gzip archive"
				case "$(od -N 1 -j 2 -t x1 "${archive}" | head -n 1 | sed 's/^.*\ //')" in
					"08")
						neko_msg normal "Compression method: deflate"
						;;
					*)
						neko_msg error "Compression method: unknown"
						;;
				esac
				case "$(od -N 1 -j 9 -t x1 "${archive}" | head -n 1 | sed 's/^.*\ //')" in
					"03")
						neko_msg normal "Made on: unix system"
						;;
					*)
						neko_msg normal "Made on: unknown"
						;;
				esac
				;;
			"4B50")
				neko_msg normal "${archive} is a zip archive"
				;;
			*)
				neko_msg normal "${archive} is an unknown archive (so far)"
				;;
		esac
	if [ -n "${distfiles}" ] || [ -n "${giturl}" ]
	then
		cd "${wrksrc}" || exit
	fi
}

neko_patch()
{
	[ -d "${patches_dir}" ] &&
		{
			for patch in "${patches_dir}"/*.patch
			do
				[ ! -f "${patch}" ] &&
					{
						neko_msg warning "There is a patches directory but no patches"
						return
					}
			done
			neko_msg normal "Applying patches for ${1}..."
			for patch in "${patches_dir}"/*.patch
			do
				neko_msg normal "Applying patch ${patch##*/}..."
				if
					patch -Np1 < "${patch}"
				then
					neko_msg normal "Successfully applied patch ${patch##*/}"
				else
					neko_msg error "Failed to apply patch ${patch##*/}"
					exit
				fi
			done
		}
}

neko_build()
{
	case "${build_style}" in
		"meta")
			:
			;;
		"makefile")
			if [ "${make_build_args}" ]
			then
				bmake CC="${CC}" -I"${DESTDIR}${PREFIX}"/include LDFLAGS=-L"${DESTDIR}${PREFIX}"/lib "${make_build_args}"
			else
				bmake CC="${CC}" -I"${DESTDIR}${PREFIX}"/include LDFLAGS=-L"${DESTDIR}${PREFIX}"/lib
			fi
			;;
		"gnu-makefile")
			if [ "${make_build_args}" ]
			then
				make CC="${CC}" -I"${DESTDIR}${PREFIX}"/include LDFLAGS=-L"${DESTDIR}${PREFIX}"/lib "${make_build_args}"
			else
				#make CC="${CC}" -I"${DESTDIR}${PREFIX}"/include LDFLAGS=-L"${DESTDIR}${PREFIX}"/lib
				make CC="${CC}"
			fi
			;;
		"configure")
			if [ "${configure_args}" ]
			then
				./configure "${configure_args}"
			else
				./configure
			fi
			if [ "${make_build_args}" ]
			then
				bmake CC="${CC}" -I"${DESTDIR}${PREFIX}"/include LDFLAGS=-L"${DESTDIR}${PREFIX}"/lib "${make_build_args}"
			else
				bmake CC="${CC}" -I"${DESTDIR}${PREFIX}"/include LDFLAGS=-L"${DESTDIR}${PREFIX}"/lib
			fi
			;;
		"gnu-configure")
			if [ "${configure_args}" ]
			then
				./configure "${configure_args}"
			else
				./configure
			fi
			if [ "${make_build_args}" ]
			then
				make CC="${CC}" -I"${DESTDIR}${PREFIX}"/include LDFLAGS=-L"${DESTDIR}${PREFIX}"/lib "${make_build_args}"
			else
				make CC="${CC}" -I"${DESTDIR}${PREFIX}"/include LDFLAGS=-L"${DESTDIR}${PREFIX}"/lib
			fi
			;;
		"meson")
			export CC=gcc # meson can only build with gcc (eww)
			meson build
			ninja -C build
			;;
		"haskell-cabal")
			:
			;;
	esac
}

neko_install()
{
	case "${build_style}" in
		"makefile" | "configure")
			if [ "${make_install_args}" ]
			then
				bmake DESTDIR="${DESTDIR}" PREFIX="${PREFIX}" "${make_install_args}" install
			else
				bmake DESTDIR="${DESTDIR}" PREFIX="${PREFIX}" install
			fi
			;;
		"gnu-makefile" | "gnu-configure")
			if [ "${make_install_args}" ]
			then
				make DESTDIR="${DESTDIR}" PREFIX="${PREFIX}" "${make_install_args}" install
			else
				make DESTDIR="${DESTDIR}" PREFIX="${PREFIX}" install
			fi
			;;
		"meson")
			ninja -C build install
			;;
		"haskell-cabal")
			cabal update
			cabal install
			;;
	esac
}

neko_license_install()
{
	[ -z "${license}" ] &&
		{
			neko_msg warning "No license specified for ${pkgname}"
			return
		}
	for pkg_license in ${license}
	do
		neko_msg normal "Installing ${pkg_license} license for ${pkgname}..."
		if
			case "${pkg_license}" in
				"MIT" | "BSD-3-Clause" | "custom")
					mkdir -p "${DESTDIR}${PREFIX}"/share/licenses/"${pkgname}"
					for licenses in ${license_file}
					do
						cp -R "${licenses}" "${DESTDIR}${PREFIX}"/share/licenses/"${pkgname}"
						chmod 644 \
							"${DESTDIR}${PREFIX}"/share/licenses/"${pkgname}"/"$(basename "${licenses}")"
					done
					;;
				"Apache-2.0")
					mkdir -p "${DESTDIR}${PREFIX}"/share/licenses/"${pkgname}"
					cp -R "${licenses_dir}"/Apache-2 "${DESTDIR}${PREFIX}"/share/licenses
					chmod 644 "${DESTDIR}${PREFIX}"/share/licenses/Apache-2
					ln -sf "${DESTDIR}${PREFIX}"/share/licenses/Apache-2 \
						"${DESTDIR}${PREFIX}"/share/licenses/"${pkgname}"/"${pkg_license}"
					;;
				"GPL-1.0-only" | "GPL-1.0-or-later")
					mkdir -p "${DESTDIR}${PREFIX}"/share/licenses/"${pkgname}"
					cp -R "${licenses_dir}"/GPL-1 "${DESTDIR}${PREFIX}"/share/licenses
					chmod 644 "${DESTDIR}${PREFIX}"/share/licenses/GPL-1
					ln -sf "${DESTDIR}${PREFIX}"/share/licenses/GPL-2 \
						"${DESTDIR}${PREFIX}"/share/licenses/"${pkgname}"/"${pkg_license}"
					;;
				"GPL-2.0-only" | "GPL-2.0-or-later")
					mkdir -p "${DESTDIR}${PREFIX}"/share/licenses/"${pkgname}"
					cp -R "${licenses_dir}"/GPL-2 "${DESTDIR}${PREFIX}"/share/licenses
					chmod 644 "${DESTDIR}${PREFIX}"/share/licenses/GPL-2
					ln -sf "${DESTDIR}${PREFIX}"/share/licenses/GPL-2 \
						"${DESTDIR}${PREFIX}"/share/licenses/"${pkgname}"/"${pkg_license}"
					;;
				"GPL-3.0-only" | "GPL-3.0-or-later")
					mkdir -p "${DESTDIR}${PREFIX}"/share/licenses/"${pkgname}"
					cp -R "${licenses_dir}"/GPL-3 "${DESTDIR}${PREFIX}"/share/licenses
					chmod 644 "${DESTDIR}${PREFIX}"/share/licenses/GPL-3
					ln -sf "${DESTDIR}${PREFIX}"/share/licenses/GPL-3 \
						"${DESTDIR}${PREFIX}"/share/licenses/"${pkgname}"/"${pkg_license}"
					;;
				"AGPL-3.0-only" | "AGPL-3.0-or-later")
					mkdir -p "${DESTDIR}${PREFIX}"/share/licenses/"${pkgname}"
					cp -R "${licenses_dir}"/AGPL-3 "${DESTDIR}${PREFIX}"/share/licenses
					chmod 644 "${DESTDIR}${PREFIX}"/share/licenses/AGPL-3
					ln -sf "${DESTDIR}${PREFIX}"/share/licenses/AGPL-3 \
						"${DESTDIR}${PREFIX}"/share/licenses/"${pkgname}"/"${pkg_license}"
					;;
				"LGPL-2-only" | "LGPL-2-or-later")
					mkdir -p "${DESTDIR}${PREFIX}"/share/licenses/"${pkgname}"
					cp -R "${licenses_dir}"/LGPL-2 "${DESTDIR}${PREFIX}"/share/licenses
					chmod 644 "${DESTDIR}${PREFIX}"/share/licenses/LGPL-2
					ln -sf "${DESTDIR}${PREFIX}"/share/licenses/LGPL-2 \
						"${DESTDIR}${PREFIX}"/share/licenses/"${pkgname}"/"${pkg_license}"
					;;
				"LGPL-2.1-only" | "LGPL-2.1-or-later")
					mkdir -p "${DESTDIR}${PREFIX}"/share/licenses/"${pkgname}"
					cp -R "${licenses_dir}"/LGPL-2.1 "${DESTDIR}${PREFIX}"/share/licenses
					chmod 644 "${DESTDIR}${PREFIX}"/share/licenses/LGPL-2.1
					ln -sf "${DESTDIR}${PREFIX}"/share/licenses/LGPL-2.1 \
						"${DESTDIR}${PREFIX}"/share/licenses/"${pkgname}"/"${pkg_license}"
					;;
				"LGPL-3-only" | "LGPL-3-or-later")
					mkdir -p "${DESTDIR}${PREFIX}"/share/licenses/"${pkgname}"
					cp -R "${licenses_dir}"/LGPL-3 "${DESTDIR}${PREFIX}"/share/licenses
					chmod 644 "${DESTDIR}${PREFIX}"/share/licenses/LGPL-3
					ln -sf "${DESTDIR}${PREFIX}"/share/licenses/LGPL-3 \
						"${DESTDIR}${PREFIX}"/share/licenses/"${pkgname}"/"${pkg_license}"
					;;
				*)
					neko_msg error "${pkg_license} is not a valid license name"
					exit
					;;
			esac
		then
			neko_msg success "Successfully installed ${pkg_license} license for ${pkgname}"
			neko_msg normal "The ${pkg_license} license for ${pkgname} can be found in:
${DESTDIR}${PREFIX}/share/licenses/${pkgname}"
		else
			neko_msg error "Failed to install ${pkg_license} license for ${pkgname}"
			exit
		fi
	done
}

neko_uninstall()
{
	while read -r pkg_file
	do
		rm -rf "${DESTDIR:?}"/"${pkg_file}"
	done < "${database}"/"${pkgname}"/INSTALL
}

neko_license_uninstall()
{
	for pkg_license in ${license}
	do
		neko_msg normal "Uninstalling ${pkg_license} license for ${pkgname}..."
		if
			rm -rf "${DESTDIR:?}"/usr/local/share/licenses/"${pkgname}"
		then
			neko_msg success "Successfully removed ${pkg_license} license for ${pkgname}"
		else
			neko_msg error "Failed to remove ${pkg_license} license for ${pkgname}"
			exit
		fi
	done
}

[ -z "${1}" ] && usage

case "${1}" in
	"init")
		neko_init
		;;
	"zap")
		neko_zap
		;;
	"pkg")
		shift 1
		for arg
		do
			if
				neko_prepare "${arg}"
				if [ -n "$(command -v "$(echo "${arg}" | sed 's/\-/_/g')"_pkg)" ]
				then
					"$(echo "${arg}" | sed 's/\-/_/g')"_pkg
				fi
				[ "${build_style}" = "meta" ] || neko_msg normal "Preparing environment..."
				[ "${deps}" ] &&
					for pkg_dep in ${deps}
					do
						if [ -n "$(command -v neko)" ]
						then
							neko pkg "${pkg_dep}"
						else
							./neko pkg "${pkg_dep}"
						fi
					done
				export CC="${CC:-tcc}"
				export DESTDIR="${master_dir}"
				export PREFIX=/usr
				for step in fetch extract patch
				do
					neko_"${step}" "${arg}"
				done
				[ "${build_style}" = "meta" ] || neko_msg normal "Building ${arg}..." &&
					if
						if [ -n "$(command -v do_build)" ]
						then
							do_build "${arg}"
							unset -f do_build
						else
							neko_build "${arg}"
						fi
					then
						neko_msg success "Successfully built ${arg}"
					else
						neko_msg error "Failed to build ${arg}"
						break
						exit
					fi
				neko_msg normal "Installing ${arg}..."
				if
					if [ -n "$(command -v do_install)" ]
					then
						do_install "${arg}"
						unset -f do_install
					else
						neko_install "${arg}"
					fi
					[ -n "$(command -v post_install)" ] &&
						{
							post_install
							unset -f post_install
						}
					neko_license_install
				then
					neko_msg success "Successfully installed ${arg}"
					neko_msg normal "Logging files into pkg database..."
					if
						mkdir -p "${database}"/"${pkgname}"
						# FIXME
						# Need a way to specify only files from ${arg}
						# Removing after every pkg will remove dependencies...
						# Solution possibly involves using diff with previous INSTALL log
						find "${DESTDIR}" -type f | sed "s|${DESTDIR}||" |
							while read -r file
							do
								printf "%s %s\n" "${file}" "$(cksum "${DESTDIR}${file}" | cut -d' ' -f1)"
							done > "${database}"/"${pkgname}"/INSTALL
					then
						neko_msg success "Successfully logged files into databse"
					else
						neko_msg error "Failed to log files into database"
						exit
					fi
				else
					neko_msg error "Failed to install ${arg}"
					break
					exit
				fi
			then
				neko_msg success "${arg} is able to be packaged"
			else
				neko_msg error "${arg} is not able to be packaged"
				exit
			fi
		done
		;;
	"clean")
		[ "$(id)" = "0" ] &&
			{
				neko_msg normal "Cleaning master directory..."
				if
					rm -rf "${root_master_dir:?}"/*
				then
					neko_msg success "Successfully cleaned master directory"
				else
					neko_msg error "Failed to clean master directory"
					exit
				fi
				neko_msg normal "Cleaning source directory..."
				if
					rm -rf "${root_src_dir:?}"/*
				then
					neko_msg success "Successfully cleaned source directory"
				else
					neko_msg error "Failed to clean source directory"
					exit
				fi
			}
		[ "$(id)" != "0" ] &&
			{
				neko_msg normal "Cleaning master directory..."
				if
					rm -rf "${master_dir:?}"/*
				then
					neko_msg success "Successfully cleaned master directory"
				else
					neko_msg error "Failed to clean master directory"
					exit
				fi
				neko_msg normal "Cleaning source directory..."
				if
					rm -rf "${src_dir:?}"/*
				then
					neko_msg success "Successfully cleaned source directory"
				else
					neko_msg error "Failed to clean source directory"
					exit
				fi
			}
		;;
	"em" | "emerge")
		[ "$(id -u)" != "0" ] &&
			{
				neko_msg error "You must have root permissions to run this command"
				exit
			}
		shift 1
		for arg
		do
			neko_prepare "${arg}"
			[ "${deps}" ] &&
				for pkg_deps in ${deps}
				do
					if [ -n "$(command -v neko)" ]
					then
						neko em "${pkg_dep}"
					else
						./neko em "${pkg_dep}"
					fi
				done
			if [ -n "$(command -v neko)" ]
			then
				neko pkg "${arg}"
			else
				./neko pkg "${arg}"
			fi
			export PREFIX=/usr
			neko_msg normal "Installing ${arg}..."
			while read -r INSTALL_LINE
			do
				mkdir -p\
					"${PREFIX}""$(dirname "$(echo "${INSTALL_LINE}" | cut -d' ' -f1)")"
				cp -R "$(echo "${master_dir}"/"${INSTALL_LINE}" | cut -d' ' -f1)"\
					"${PREFIX}""$(echo "${INSTALL_LINE}" | cut -d' ' -f1)"
			done < "${database}"/"${pkgname}"/INSTALL
		done
		;;
	"uninstall")
		[ "$(id -u)" != "0" ] &&
			{
				neko_msg error "You must have root permissions to run this command"
				exit
			}
		shift 1
		for arg
		do
			neko_msg normal "Uninstalling ${arg}..."
			if
				neko_uninstall "${arg}"
				neko_license_uninstall
			then
				neko_msg success "Successfully uninstalled ${arg}"
			else
				neko_msg error "Failed to uninstall ${arg}"
			fi
		done
		;;
	"new")
		[ -d "${pkgs_dir}"/"${2}" ] &&
			{
				neko_msg error "There's already a template for ${2}"
				exit
			}
		neko_msg normal "Making a base template for ${2}..."
		if
			mkdir -p "${pkgs_dir}"/"${2}"
			{
				cat << _EOF
pkgname="${2}"
short_desc="Describe the pkg shortly"
deps="deps go here"
version="1.0"
revision="1"
distfiles="https://url.to/source/pkgname-\${version}.tar.gz"
#archive="\${distfiles##*/}"
#wrksrc="\${pkgname}-\${version}"
build_style="makefile"
#make_build_args="CC=\${CC}"
#make_install_args="DESTDIR=\${DESTDIR}"
license="GPL-3.0-or-later"

#do_build()
#{
#	make "\${make_build_args}"
#}

#do_install()
#{
#	make "\${make_install_args}" install
#}
_EOF
			} >> "${pkgs_dir}"/"${2}"/template
		then
			neko_msg success "Made a template for ${2} in ${pkgs_dir}/${2}"
			vi "${pkgs_dir}"/"${2}"/template
		else
			neko_msg error "Failed to make a template for ${2}"
		fi
		;;
	"find")
		shift 1
		for arg
		do
			neko_msg normal "$(find "${pkgs_dir}" -name "*${arg}*" | wc -l) result(s) found for ${arg}"
			# FIXME
			# POSIX -exec printf '%s\n' '{}' '+' produces unexpected behaviour
			# FIXME
			# neko find doesn't update short_desc for sub packages
			# TODO
			# Redo neko find from scratch at this point...
			for pkg_found in $(find "${pkgs_dir}" ! -name srcpkgs -prune -name "*${arg}*" -print0 | xargs -0 -n1 basename 2> /dev/null)
			do
				. "${pkgs_dir}"/"${pkg_found}"/template
				[ "${distfiles}" ] && [ "${version}" ] &&
					printf "%s\t%s\n" "[1m${pkg_found}-${version}_${revision}[0m" "${short_desc}"
				[ "${build_style}" = "meta" ] &&
					printf "%s\t%s\n" "[1m${pkg_found}_${revision}[0m" "${short_desc}"
				[ "${giturl}" ] &&
					printf "%s\t%s\n" "[1m${pkg_found}[0m" "${short_desc}"
				unset version
				unset giturl
			done
		done
		;;
	"help")
		help
		;;
	*)
		neko_msg error "Unknown option ${1}"
		neko_msg normal "Use neko help"
esac
