.TH NEKO 1
.SH NAME
neko \- package manager written in POSIX shell / utilities
.SH SYNOPSIS
.B neko
COMMANDS [\fIOPTIONS\fR] [\fITARGET\fR]
.SH DESCRIPTION
This is a WIP package manager inspired by VOID's xbps-src bash script package builder.
.SH COMMANDS
.TP
.BR "help [\fICOMMAND\fR]"
Quick way to get help for \fICOMMAND\fR
.TP
.BR "pkg \fIPKG\fR"
Will build and install \fIPKG\fR into the master root directory
.TP
.BR "em, emerge \fIPKG\fR"
Will build \fIPKG\fR into the master directory and install to the chosen system
.TP
.BR "uninstall \fIPKG\fR"
Will uninstall \fIPKG\fR from the chosen system
.TP
.BR "find \fIPKG\fR"
Will search for and list \fIPKG\fR from srcpkgs with the short description
.TP
.BR "clean"
Cleans up the master root directory and master source directory
