#!/bin/sh

# neko sources files depending on arguments
# shellcheck source=/dev/null
# some variables are sourced from the specified template
# shellcheck disable=SC2154
# Unused variables left for readability
# shellcheck disable=SC2034

root_base_dir="${DESTDIR}"/usr/local/share/neko
root_pkgs_dir="${root_base_dir}"/srcpkgs
root_src_dir="${root_base_dir}"/src
root_master_dir="${root_master_dir}"/master
root_license_dir="${root_base_dir}"/licenses
root_db_dir="${root_base_dir}"/db

base_dir="${XDG_DATA_HOME:-$HOME/.local/share}"/neko
pkgs_dir="${base_dir}"/srcpkgs
src_dir="${base_dir}"/src
master_dir="${base_dir}"/master
licenses_dir="${base_dir}"/licenses
db_dir="${base_dir}"/db

trap interrupt 2

neko_msg()
{
	case "${1}" in
		"normal") echo "\033[1m=> \033[36mneko:\033[0m ${2}" ;;
		"success") echo "\033[1m=> \033[32mneko:\033[0m ${2}" ;;
		"warning") echo "\033[1m=> \033[33mneko:\033[0m ${2}" ;;
		"error") echo "\033[1m=> \033[31mneko:\033[0m ${2}" ;;
	esac
}

usage()
{
	cat << _EOF
[1musage[0m
neko [command] <target>

[1mcommand[0m:
init
	Initializes the environment for use with the templates - must be run before
	packaging from templates.
pkg
	Checks to see if the <target> can be properly packaged from the template.
em | emerge
	Emerges the <target>. Will build and install it to the system.
uninstall
	Will uninstall <target> to the system.
find
	Will search for the <target>
clean
	Cleans up the master directory.
zap
	Will remove everything from the neko directory - you must run neko init
	after doing so.
help
	Displays this message

[1mstatus[0m:
Neko will have different colors depending on the status:
$(neko_msg normal "This is a normal message.")
$(neko_msg success "This is a successful message.")
$(neko_msg warning "This is a warning message.")
$(neko_msg error "This is an error message.")
_EOF
}

interrupt()
{
	# to start on a new line
	echo ""
	neko_msg error "Command interrupted"
	exit 1
}

# pkg_install and pkg_uninstall are only used in templates
pkg_install()
{
	case "${1}" in
		"bin")
			echo "Installing $(basename "${2}")..."
			if
				mkdir -p "${DESTDIR}"/usr/local/bin
				cp -r "${2}" "${DESTDIR}"/usr/local/bin
				chmod 755 "${DESTDIR}"/usr/local/bin/"$(basename "${2}")"
			then
				echo "Successfully installed ${2}"
			else
				echo "Failed to install ${2}"
			fi
			;;
		"man")
			echo "Installing $(basename "${2}")..."
			if
				mkdir -p "${DESTDIR}"/usr/local/share/man/man"${3:-1}"
				cp -r "${2}" "${DESTDIR}"/usr/local/share/man/man"${3:-1}"
				chmod 644 "${DESTDIR}"/usr/local/share/man/man"${3:-1}"/"$(basename "${2}")"
			then
				echo "Successfully installed ${2}"
			else
				echo "Failed to install ${2}"
			fi
			;;
		"lib")
			echo "Installing $(basename "${2}")..."
			if
				mkdir -p "${DESTDIR}"/usr/local/lib"${3}"
				cp -r "${2}" "${DESTDIR}"/usr/local/lib"${3}"
				chmod 644 "${DESTDIR}"/usr/local/lib"${3}"/"$(basename "${2}")"
			then
				echo "Successfully installed ${2}"
			else
				echo "Failed to install ${2}"
			fi
			;;
		"inc")
			echo "Installing $(basename "${2}")..."
			if
				mkdir -p "${DESTDIR}"/usr/local/include"${3}"
				cp -r "${2}" "${DESTDIR}"/usr/local/include"${3}"
				chmod 644 "${DESTDIR}"/usr/local/include"${3}"/"$(basename "${2}")"
			then
				echo "Successfully installed ${2}"
			else
				echo "Failed to install ${2}"
			fi
			;;
		"conf")
			echo "Installing $(basename "${2}")..."
			if
				mkdir -p "${DESTDIR}"/etc"${3}"
				cp -r "${2}" "${DESTDIR}"/etc"${3}"
				chmod 644 "${DESTDIR}"/etc"${3}"/"$(basename "${2}")"
			then
				echo "Successfully installed ${2}"
			else
				echo "Failed to install ${2}"
			fi
			;;
		"file")
			pkg_install file README 644 /usr/share/doc
			echo "Installing $(basename "${2}")..."
			if
				mkdir -p "${DESTDIR}"/usr/local"${4}"
				cp -r "${2}" "${DESTDIR}"/usr/local"${4}"
				chmod "${3}" "${DESTDIR}"/usr/local"${4}"/"${2}"
			then
				echo "Successfully installed $(basename "${2}")"
			else
				echo "Failed to install $(basename "${2}")"
			fi
			;;
	esac
}

neko_init()
{
	for dir in "${base_dir}" "${pkgs_dir}" "${src_dir}" "${master_dir}"\
		"${licenses_dir}" "${db_dir}"
	do
		[ ! -d "${dir}" ] && neko_msg normal "Making dir ${dir}..." &&
			if
				mkdir -p "${dir}"
			then
				neko_msg success "Successfully made dir ${dir}"
			else
				neko_msg error "Failed to make dir ${dir}"
				exit
			fi
	done
	neko_msg normal "Copying base srcpkgs to ${base_dir}..."
	if
		cp -r srcpkgs "${base_dir}"
	then
		neko_msg success "Successfully copied base srcpkgs to ${base_dir}"
	else
		neko_msg error "Failed to copy base srcpkgs to ${base_dir}"
		exit
	fi
	neko_msg normal "Copying licenses to ${base_dir}..."
	if
		cp -r licenses "${base_dir}"
	then
		neko_msg success "Successfully copied licenses to ${base_dir}"
	else
		neko_msg error "Failed to copy licenses to ${base_dir}..."
		exit
	fi
}

neko_zap()
{
	neko_msg normal "Zapping neko directory ${base_dir}..."
	if
		rm -rf "${base_dir:?}"/*
	then
		neko_msg success "Successfully zapped neko directory"
	else
		neko_msg error "Failed to zap neko directory"
		exit
	fi

}

neko_prepare()
{
	[ ! -d "${pkgs_dir}" ] && [ ! -d "${root_pkgs_dir}" ] &&
		{
			neko_msg error "No base srcpkgs found in ${base_dir}"
			neko_msg normal "Run neko init"
			exit
		}
	[ ! -d "${master_dir}" ] && [ ! -d "${root_master_dir}" ] &&
		{
			neko_msg error "No master dir found in ${base_dir}"
			neko_msg normal "Run neko init"
			exit
		}
	[ ! -d "${src_dir}" ] && [ ! -d "${root_src_dir}" ] &&
		{
			neko_msg error "No master dir found in ${base_dir}"
			neko_msg normal "Run neko init"
			exit
		}
	[ ! -d "${licenses_dir}" ] && [ ! -d "${root_license_dir}" ] &&
		{
			neko_msg error "No master dir found in ${base_dir}"
			neko_msg normal "Run neko init"
			exit
		}
	[ ! -d "${db_dir}" ] && [ ! -d "${root_db_dir}" ] &&
		{
			neko_msg error "No databse dir found in ${base_dir}"
			neko_msg normal "Run neko init"
			exit
		}
	if [ -f "${pkgs_dir}"/"${1}"/template ]
	then
		template_file="${pkgs_dir}"/"${1}"/template
		patches_dir="${pkgs_dir}"/"${1}"/patches
		files_dir="${pkgs_dir}"/"${1}"/files
		source_dir="${src_dir}"
		database="${base_dir}"/db
	elif [ -f "${root_pkgs_dir}"/"${1}"/template ]
	then
		template_file="${root_pkgs_dir}"/"${1}"/template
		patches_dir="${root_pkgs_dir}"/"${1}"/patches
		files_dir="${root_pkgs_dir}"/"${1}"/files
		sourse_dir="${root_src_dir}"
		database="${root_base_dir}"/db
	else
		neko_msg error "No template found for ${1}"
		exit
	fi
	. "${template_file}"
	if [ "${distfiles}" ]
	then
		wrksrc="${pkgname}"-"${version}"
	elif [ "${giturl}" ]
	then
		wrksrc="$(echo "${pkgname}" | sed 's/-git//')"
	fi
	archive="${distfiles##*/}"
	# Try and use TCC by default
	if [ "${TCC}" = "false" ]
	then
		export CC=cc
	else
		export CC=tcc
	fi
	# Allow override of wrksrc and archive
	. "${template_file}"
}

neko_fetch()
{
	# Remove duplicate wrksrc
	[ -d "${source_dir}"/"${wrksrc}" ] && [ "${build_style}" != "meta" ] &&
		rm -rf "${source_dir:?}"/"${wrksrc:?}"
	# Remove duplicate archive
	[ "${distfiles}" ] && [ -f "${source_dir}"/"${archive}" ] &&
		[ "${build_style}" != "meta" ] && rm -rf "${source_dir:?}"/"${archive:?}"
	cd "${source_dir}" || exit
	[ "${build_style}" = "meta" ] && return
	neko_msg normal "Downloading source for ${1}..."
	if [ "${distfiles}" ]
	then
		if
			wget "${distfiles}"
		then
			neko_msg success "Successfully fetched distfiles for ${1}"
		else
			neko_msg error "Failed to fetch distfiles for ${1}"
			exit
		fi
	elif [ "${giturl}" ]
	then
		if
			git clone "${giturl}"
		then
			neko_msg success "Successfully cloned git repo for ${1}"
		else
			neko_msg error "Failed to clone git repo for ${1}"
			exit
		fi
	else
		[ "${build_style}" != "meta" ] &&
			{
				neko_msg error "No distfiles or giturl specified"
				exit
			}
	fi
}

neko_extract()
{
	[ "${build_style}" = "meta" ] && return
	[ "${distfiles}" ] && neko_msg normal "Extracting distfiles for ${1}..."
	[ "${distfiles}" ] &&
		if
			case "${archive##*.}" in
				"gz" | "tgz")
					tar -zxvf "${archive}"
					;;
				"bz2" | "xz")
					tar -xvf "${archive}"
					;; 
			esac
		then
			neko_msg success "Successfully extracted distfiles for ${pkgname}"
		else
			neko_msg error "Failed to extract distfiles for ${pkgname}"
			exit
		fi
	# Testing for replacing GNU tar with dd and od commands
	case "$(od -N 2 -t x2 "${archive}" | head -n 1 | cut -d' ' -f2)" in
		"8b1f")
			neko_msg normal "${archive} is a gzip archive"
			case "$(od -N 1 -j 2 -t x1 "${archive}" | head -n 1 | cut -d' ' -f2)" in
				"08")
					neko_msg normal "Compression method: deflate"
					;;
				*)
					neko_msg error "Compression method: unknown"
					;;
			esac
			case "$(od -N 1 -j 9 -t x1 "${archive}" | head -n 1 | cut -d' ' -f2)" in
				"03")
					neko_msg normal "Made on: unix system"
					;;
				*)
					neko_msg normal "Made on: unknown"
					;;
			esac
			;;
		"4B50")
			neko_msg normal "${archive} is a zip archive"
			;;
		*)
			neko_msg error "${archive} is an unknown archive"
			;;
	esac
	cd "${wrksrc}" || exit
}

neko_patch()
{
	if [ -d "${patches_dir}" ]
	then
		neko_msg normal "Applying patches for ${1}..."
		for patch in "${patches_dir}"/*.patch
		do
			neko_msg normal "Applying patch ${patch##*/}..."
			if
				patch -Np1 < "${patch}"
			then
				neko_msg normal "Successfully applied patch ${patch##*/}"
			else
				neko_msg error "Failed to apply patch ${patch##*/}"
				exit
			fi
		done
	fi
}

neko_build()
{
	case "${build_style}" in
		"meta")
			:
			;;
		"makefile")
			if [ "${make_build_args}" ]
			then
				bmake "${make_args}"
			else
				bmake
			fi
			;;
		"gnu-makefile")
			if [ "${make_build_args}" ]
			then
				make "${make_args}"
			else
				make
			fi
			;;
		"configure")
			if [ "${configure_args}" ]
			then
				./configure "${configure_args}"
			else
				./configure
			fi
			if [ "${make_build_args}" ]
			then
				bmake "${make_build_args}"
			else
				bmake
			fi
			;;
		"gnu-configure")
			if [ "${configure_args}" ]
			then
				./configure "${configure_args}"
			else
				./configure
			fi
			if [ "${make_build_args}" ]
			then
				make "${make_build_args}"
			else
				make
			fi
			;;
		"meson")
			export CC=cc # meson can't build with tcc compiler
			meson build
			ninja -C build
			;;
		"haskell-cabal")
			:
			;;
	esac
}

neko_install()
{
	case "${build_style}" in
		"makefile" | "configure")
			if [ "${make_install_args}" ]
			then
				bmake "${make_install_args}" install
			else
				bmake install
			fi
			;;
		"gnu-makefile" | "gnu-configure")
			if [ "${make_install_args}" ]
			then
				make "${make_install_args}" install
			else
				make install
			fi
			;;
		"meson")
			ninja -C build install
			;;
		"haskell-cabal")
			cabal update
			cabal install
			;;
	esac
}

neko_license_install()
{
	for pkg_license in ${license}
	do
		neko_msg normal "Installing ${pkg_license} license for ${pkgname}..."
		if
			case "${pkg_license}" in
				"MIT" | "BSD-3-Clause" | "custom")
					mkdir -p "${DESTDIR}"/usr/local/share/licenses/"${pkgname}"
					for licenses in ${license_file}
					do
						cp -r "${licenses}" "${DESTDIR}"/usr/local/share/licenses/"${pkgname}"
						chmod 644 \
							"${DESTDIR}"/usr/local/share/licenses/"${pkgname}"/"$(basename "${licenses}")"
					done
					;;
				"GPL-1.0-only" | "GPL-1.0-or-later")
					mkdir -p "${DESTDIR}"/usr/local/share/licenses/"${pkgname}"
					cp -r "${licenses_dir}"/GPL-1 "${DESTDIR}"/usr/local/share/licenses
					chmod 644 "${DESTDIR}"/usr/local/share/licenses/GPL-1
					ln -sf "${DESTDIR}"/usr/local/share/licenses/GPL-2 \
						"${DESTDIR}"/usr/local/share/licenses/"${pkgname}"/"${pkg_license}"
					;;
				"GPL-2.0-only" | "GPL-2.0-or-later")
					mkdir -p "${DESTDIR}"/usr/local/share/licenses/"${pkgname}"
					cp -r "${licenses_dir}"/GPL-2 "${DESTDIR}"/usr/local/share/licenses
					chmod 644 "${DESTDIR}"/usr/local/share/licenses/GPL-2
					ln -sf "${DESTDIR}"/usr/local/share/licenses/GPL-2 \
						"${DESTDIR}"/usr/local/share/licenses/"${pkgname}"/"${pkg_license}"
					;;
				"GPL-3.0-only" | "GPL-3.0-or-later")
					mkdir -p "${DESTDIR}"/usr/local/share/licenses/"${pkgname}"
					cp -r "${licenses_dir}"/GPL-3 "${DESTDIR}"/usr/local/share/licenses
					chmod 644 "${DESTDIR}"/usr/local/share/licenses/GPL-3
					ln -sf "${DESTDIR}"/usr/local/share/licenses/GPL-3 \
						"${DESTDIR}"/usr/local/share/licenses/"${pkgname}"/"${pkg_license}"
					;;
				"AGPL-3.0-only" | "AGPL-3.0-or-later")
					mkdir -p "${DESTDIR}"/usr/local/share/licenses/"${pkgname}"
					cp -r "${licenses_dir}"/AGPL-3 "${DESTDIR}"/usr/local/share/licenses
					chmod 644 "${DESTDIR}"/usr/local/share/licenses/AGPL-3
					ln -sf "${DESTDIR}"/usr/local/share/licenses/AGPL-3 \
						"${DESTDIR}"/usr/local/share/licenses/"${pkgname}"/"${pkg_license}"
					;;
				"LGPL-2-only" | "LGPL-2-or-later")
					mkdir -p "${DESTDIR}"/usr/local/share/licenses/"${pkgname}"
					cp -r "${licenses_dir}"/LGPL-2 "${DESTDIR}"/usr/local/share/licenses
					chmod 644 "${DESTDIR}"/usr/local/share/licenses/LGPL-2
					ln -sf "${DESTDIR}"/usr/local/share/licenses/LGPL-2 \
						"${DESTDIR}"/usr/local/share/licenses/"${pkgname}"/"${pkg_license}"
					;;
				"LGPL-2.1-only" | "LGPL-2.1-or-later")
					mkdir -p "${DESTDIR}"/usr/local/share/licenses/"${pkgname}"
					cp -r "${licenses_dir}"/LGPL-2.1 "${DESTDIR}"/usr/local/share/licenses
					chmod 644 "${DESTDIR}"/usr/local/share/licenses/LGPL-2.1
					ln -sf "${DESTDIR}"/usr/local/share/licenses/LGPL-2.1 \
						"${DESTDIR}"/usr/local/share/licenses/"${pkgname}"/"${pkg_license}"
					;;
				"LGPL-3-only" | "LGPL-3-or-later")
					mkdir -p "${DESTDIR}"/usr/local/share/licenses/"${pkgname}"
					cp -r "${licenses_dir}"/LGPL-3 "${DESTDIR}"/usr/local/share/licenses
					chmod 644 "${DESTDIR}"/usr/local/share/licenses/LGPL-3
					ln -sf "${DESTDIR}"/usr/local/share/licenses/LGPL-3 \
						"${DESTDIR}"/usr/local/share/licenses/"${pkgname}"/"${pkg_license}"
					;;
				*)
					:
					;;
			esac
		then
			neko_msg success "Successfully installed ${pkg_license} license for ${pkgname}"
			neko_msg normal "The ${pkg_license} license for ${pkgname} can be found in:
${DESTDIR}/usr/local/share/licenses/${pkgname}"
		else
			neko_msg error "Failed to install ${pkg_license} license for ${pkgname}"
			exit
		fi
	done
}

neko_uninstall()
{
	while read -r pkg_file
	do
		rm -rf "${DESTDIR:?}"/"${pkg_file}"
	done < "${database}"/"${pkgname}"/INSTALL
}

neko_license_uninstall()
{
	for pkg_license in ${license}
	do
		neko_msg normal "Uninstalling ${pkg_license} license for ${pkgname}..."
		if
			rm -rf "${DESTDIR:?}"/usr/local/share/licenses/"${pkgname}"
		then
			neko_msg success "Successfully removed ${pkg_license} license for ${pkgname}"
		else
			neko_msg error "Failed to remove ${pkg_license} license for ${pkgname}"
			exit
		fi
	done
}

case "${1}" in
	"init")
		neko_init
		;;
	"zap")
		neko_zap
		;;
	"pkg")
		shift 1
		neko_msg normal "Cleaning master dir..."
		if
			rm -rf "${master_dir:?}"/*
		then
			neko_msg success "Successfully cleaned master dir"
		else
			neko_msg error "Failed to clean master dir"
			exit
		fi
		for arg
		do
			if
				neko_prepare "${arg}"
				[ "${build_style}" = "meta" ] || neko_msg normal "Preparing environment..."
				[ "${deps}" ] &&
					for pkg_dep in ${deps}
					do
						if [ -n "$(command -v neko)" ]
						then
							neko pkg "${pkg_dep}"
						else
							./neko pkg "${pkg_dep}"
						fi
					done
				for step in fetch extract patch
				do
					neko_"${step}" "${arg}"
				done
				[ "${build_style}" = "meta" ] || neko_msg normal "Building ${arg}..." &&
					if
						if [ -n "$(command -v do_build)" ]
						then
							do_build "${arg}"
							unset -f do_build
						else
							neko_build "${arg}"
						fi
					then
						neko_msg success "Successfully built ${arg}"
					else
						neko_msg error "Failed to build ${arg}"
						break
						exit
					fi
				export DESTDIR="${master_dir}"
				neko_msg normal "Installing ${arg}..."
				if
					if [ -n "$(command -v do_install)" ]
					then
						do_install "${arg}"
						unset -f do_install
					else
						neko_install "${arg}"
					fi
					[ -n "$(command -v post_install)" ] &&
						{
							post_install
							unset -f post_install
						}
					neko_license_install
				then
					neko_msg success "Successfully installed ${arg}"
					neko_msg normal "Logging files into pkg database..."
					if
						mkdir -p "${database}"/"${pkgname}"
						for line in $(find "${DESTDIR}" -type f)
						do
							printf "%s %s\n" "$(echo "${line}" | sed "s|^${DESTDIR}||")"\
								"$(cksum "${line}" | cut -d' ' -f1)"
						done > "${database}"/"${pkgname}"/INSTALL
					then
						neko_msg success "Successfully logged files into databse"
					else
						neko_msg error "Failed to log files into database"
						exit
					fi
				else
					neko_msg error "Failed to install ${arg}"
					break
					exit
				fi
			then
				neko_msg success "${arg} is able to be packaged"
			else
				neko_msg error "${arg} is not able to be packaged"
				exit
			fi
		done
		;;
	"clean")
		neko_msg normal "Cleaning master directory..."
		if
			rm -rf "${master_dir:?}"/*
		then
			neko_msg success "Successfully cleaned master directory"
		else
			neko_msg error "Failed to clean master directory"
			exit
		fi
		;;
	"em" | "emerge")
		[ "$(id -u)" != "0" ] &&
			{
				neko_msg error "You must have root permissions to run this command"
				exit
			}
		shift 1
		for arg
		do
			neko_prepare "${arg}"
			[ "${deps}" ] &&
				for pkg_deps in ${deps}
				do
					if [ -n "$(command -v neko)" ]
					then
						neko em "${pkg_dep}"
					else
						./neko em "${pkg_dep}"
					fi
				done
			if [ -n "$(command -v neko)" ]
			then
				neko pkg "${arg}"
			else
				./neko pkg "${arg}"
			fi
			export PREFIX=/
			neko_msg normal "Installing ${arg}..."
			while read -r INSTALL_LINE
			do
				mkdir -p\
					"${PREFIX}""$(dirname "$(echo "${INSTALL_LINE}" | cut -d' ' -f1)")"
				cp -r "$(echo "${master_dir}"/"${INSTALL_LINE}" | cut -d' ' -f1)"\
					"${PREFIX}""$(echo "${INSTALL_LINE}" | cut -d' ' -f1)"
			done < "${database}"/"${pkgname}"/INSTALL
		done
		;;
	"uninstall")
		[ "$(id -u)" != "0" ] &&
			{
				neko_msg error "You must have root permissions to run this command"
				exit
			}
		shift 1
		for arg
		do
			neko_msg normal "Uninstalling ${arg}..."
			if
				neko_uninstall "${arg}"
				neko_license_uninstall
			then
				neko_msg success "Successfully uninstalled ${arg}"
			else
				neko_msg error "Failed to uninstall ${arg}"
			fi
		done
		;;
	"new")
		[ -d "${pkgs_dir}"/"${2}" ] &&
			{
				neko_msg error "There's already a template for ${2}"
				exit
			}
		neko_msg normal "Making a base template for ${2}..."
		if
			mkdir -p "${pkgs_dir}"/"${2}"
			{
			echo "pkgname=\"${2}\""
			echo "short_desc=\"Describe this pkg shortly\""
			echo "version=\"1.0\""
			echo "revision=\"1\""
			echo "distfiles=\"url.to/source-\${version}.tar.gz\""
			echo "build_style=\"makefile\""
			echo "license=\"GPL-3.0-or-later\""
			} >> "${pkgs_dir}"/"${2}"/template
		then
			neko_msg success "Made a template for ${2} in ${pkgs_dir}/${2}"
			vi "${pkgs_dir}"/"${2}"/template
		else
			neko_msg error "Failed to make a template for ${2}"
		fi
		;;
	"find")
		shift 1
		for arg
		do
			neko_msg normal "$(find  "${pkgs_dir}" -name "*${arg}*" | wc -l) result(s) found for ${arg}"
			for pkg_found in $(find  "${pkgs_dir}" -name "*${arg}*" | sed "s|^${pkgs_dir}/||")
			do
				. "${pkgs_dir}"/"${pkg_found}"/template
				[ "${distfiles}" ] && [ "${version}" ] &&
					printf "%s\t%s\n" "[1m${pkg_found}-${version}_${revision}[0m" "${short_desc}"
				[ "${build_style}" = "meta" ] &&
					printf "%s\t%s\n" "[1m${pkg_found}_${revision}[0m" "${short_desc}"
				[ "${giturl}" ] &&
					printf "%s\t%s\n" "[1m${pkg_found}[0m" "${short_desc}"
				unset version
				unset giturl
			done
		done
		;;
	"help")
		usage
		;;
	*)
		neko_msg error "Unknown option ${1}"
		neko_msg normal "Use neko help"
esac
