.TH NEKO 1
.SH NAME
neko \- package builder / installer (WIP)
.SH SYNOPSIS
.B neko
[\fIOPTIONS\fR] [\fIPKG\fR]
.SH DESCRIPTION
This is a WIP package builder / installer inspired by VOID's xbps-src bash script.
.SH OPTIONS
.TP
.BR "clean"
Cleans up the master directory
.TP
.BR "pkg \fIPKG\fR"
Will build \fIPKG\fR into the master directory
.TP
.BR "em, emerge \fIPKG\fR"
Will build \fIPKG\fR into the master directory and install to the system
.TP
.BR "uninstall \fIPKG\fR"
Will uninstall \fIPKG\fR from the system
