#!/bin/sh

neko_msg()
{
	case "${1}" in
		"normal") echo "\033[1m=> \033[36mneko\033[0m: ${2}" ;;
		"success") echo "\033[1m=> \033[32mneko\033[0m: ${2}" ;;
		"warning") echo "\033[1m=> \033[33mneko\033[0m: ${2}" ;;
		"error") echo "\033[1m=> \033[31mneko\033[0m: ${2}" ;;
		*) echo "\033[1m=> \033[36mneko\033m: ${2} - please specify an urgency"
	esac
}
