#!/bin/sh

do_fetch()
{
	if [ "${distfiles}" ]; then
		neko_msg normal "Fetching distfiles for ${1}..."
		wget "${distfiles}" &&
			neko_msg success "Successfully fetched distfiles!" ||
			{ neko_msg error "Failed to fetch distfiles!" && exit 1; }
	elif [ "${giturl}" ]; then
		[ -d ${pkgname} ] && rm -rf ${pkgname}
		neko_msg normal "Cloning git repo for ${1}..."
		git clone "${giturl}" &&
			neko_msg success "Successfully cloned git repo!" ||
			{ neko_msg error "Failed to clone git repo!" && exit 1; }
	else
		neko_msg error "No distfiles or git url specified for ${1}"
	fi
}
