#!/bin/sh

# Source as do_uninstall doesn't do_prepare
. srcpkgs/"${2}"/template

do_uninstall()
{
	case "${build_style}" in
		"makefile")
			neko_msg normal "Uninstalling ${1}..."
			make uninstall &&
				neko_msg success "Successfully uninstalled ${1}!" ||
				{ neko_msg error "Failed to uninstall ${1}!" && exit 1; }
			;;
	esac
}

# Allow for overrides in template
. srcpkgs/"${2}"/template
