#!/bin/sh

do_prepare()
{
	# Check for permissions
	[ $(logname) = "root" ] && perms="root" || perms="anon"
	neko_msg normal "Preparing environment for building..."
	[ ! -f srcpkgs/"${1}"/template ] && neko_msg error "No template for ${1}" && exit 1;
	patches_dir="srcpkgs/"${1}"/patches"
	. srcpkgs/"${1}"/template
	archive=${pkgname}-${version}.tar.gz
	if [ "${giturl}" ]
	then
		wrksrc="${pkgname}"
	else
		wrksrc="${pkgname}-${version}"
	fi
	# Source again to allow overrides
	. srcpkgs/"${1}"/template
	cd master || exit
	[ -d "${wrksrc}" ] && rm -rf "${wrksrc}"
}
