#!/bin/sh

do_patch()
{
	for file in ../"${patches_dir}"/*.patch
	do
		[ -d ../"${patches_dir}" ] && [ ! -f "${file}" ] && neko_msg warning "There is a patches directory, but no patches."
	done
	if [ -d ../"${patches_dir}" ]
	then
		cd "${wrksrc}" || exit
		neko_msg normal "Applying patches for ${1}..."
		for patch in ../../"${patches_dir}"/*.patch
		do
			neko_msg normal "Applying patch ${patch##*/}..."
			patch -Np1 < "${patch}"
		done &&
			neko_msg success "Successfully applied patches!" ||
			{ neko_msg error "Failed to apply one or more patches!" && exit 1; }
		cd ..
	fi
}
